language: go

go_import_path: github.com/lightyeario/kelp

go:
- "1.10.x"
- "1.11"

before_install:
- curl https://glide.sh/get | sh

install:
- glide install

script:
- ./scripts/build.sh
- ./bin/kelp version
