version: 2.1
commands:
  install_deps:
    steps:
      - checkout
      - restore_cache:
          keys:
            - v3-pkg-cache
            - v5-node-cache
      - run:
          name: Install glide
          command: curl https://glide.sh/get | sh
      - run:
          name: Install dependencies using glide
          command: glide install
      - run:
          name: Fetch astilectron-bundler
          command: go get -u github.com/asticode/go-astilectron-bundler/...
      - run:
          name: Install astilectron-bundler
          command: go install github.com/asticode/go-astilectron-bundler
      - run:
          name: Install nvm
          command: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash
      - run:
          name: Use Node 10.5
          command: echo 'export NVM_DIR=$HOME/.nvm' >> $BASH_ENV && echo 'source $NVM_DIR/nvm.sh' >> $BASH_ENV && source $BASH_ENV && nvm install 10.17 && nvm use 10.17
      - run:
          name: Install yarn
          command: curl -o- -L https://yarnpkg.com/install.sh | bash
      - run:
          name: Use yarn
          command: echo 'export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"' >> $BASH_ENV && source $BASH_ENV
      - save_cache:
          key: v3-pkg-cache
          paths:
            - "/go/src/github.com/stellar/kelp/vendor"

  test_kelp:
    steps:
      - run:
          name: Run Kelp tests
          command: go test --short ./...

  build_kelp:
    steps:
      - run:
          name: Build Kelp
          command: ./scripts/build.sh
      - save_cache:
          key: v5-node-cache
          paths:
            - "/go/src/github.com/stellar/kelp/gui/web/node_modules"
      - run:
          name: Ensure build was successful
          command: ./bin/kelp version

jobs:
  # test performs all package tests from Kelp
  test_1_10:
    working_directory: /go/src/github.com/stellar/kelp
    docker:
      - image: circleci/golang:1.10
      - image: franzsee/ccxt-rest:v0.0.4
        command: ["node", "/usr/local/bin/ccxt-rest"]

    steps:
      - install_deps
      - build_kelp
      - test_kelp

  test_1_11:
    working_directory: /go/src/github.com/stellar/kelp
    docker:
      - image: circleci/golang:1.11
      - image: franzsee/ccxt-rest:v0.0.4
        command: ["node", "/usr/local/bin/ccxt-rest"]

    steps:
      - install_deps
      - build_kelp
      - test_kelp

  test_1_12:
    working_directory: /go/src/github.com/stellar/kelp
    docker:
      - image: circleci/golang:1.12
      - image: franzsee/ccxt-rest:v0.0.4
        command: ["node", "/usr/local/bin/ccxt-rest"]

    steps:
      - install_deps
      - build_kelp
      - test_kelp

workflows:
  version: 2
  build-and-test:
    jobs:
      - test_1_10
      - test_1_11
      - test_1_12
